New sample file testing IfcLinearPlacement and related concepts
buildingSMART/Sample-Test-Files pull request #23
Opened 2020-09-11 07:19 UTC by seb-esser

# New Sample for IfcLinearPlacement

Fixes: likely nothing but might raise attention to issues around the linear positioning concept

## Changes and improvements proposed by this pull request
- LinPlacement sample 2

fyi:
@jmirtsch @pjanck @NigelPMPeters @SergejMuhic @larswik 

# IFC4.3 Unit test

## Unit test
not decided yet - file could help developers to get a solid starting point when implementing alignment and linear referencing methods in recent IFC versions

## Review requested
- IfcAlignment and its axis should be ok
- IfcBuildingElementProxy instances should be ok
- FZK Viewer reports an issue on the `IfcShapeRepresentation`: 
![grafik](https://user-images.githubusercontent.com/56266373/92881728-88800700-f40f-11ea-9f8b-4d0337553cc6.png)
Any feedback and suggestions for improvements are highly appreciated

2020-09-11 09:55 UTC, larswik commented
There are a number of IFCPRESENTATIONLAYERASSIGNMENT that references entities that doesn't exist. I also get some geometric errors (not telling me much at this stage). However, your issue on shape representation, I dont get in my version (6.0 - build 1658) of FZKViewer. Otherwise, it looks fine to me!
![image](https://user-images.githubusercontent.com/25506404/92906667-f2ef7200-f424-11ea-899b-829152a3d676.png)

2020-09-17 09:20 UTC, larswik reviewed
Why change the FILE_SCHEMA to 'IFC4X3RC1' without the underscore? Otherwise fine by me.

2020-09-18 12:27 UTC, pjanck requested changes
Minor changes in the header. Otherwise LFTM.

2020-09-18 12:27 UTC, pjanck commented on IFC 4.3/LinearPlacement_2/LinearPlacement_2.ifc
> +FILE_SCHEMA (('IFC4X3RC1'));
```suggestion
FILE_SCHEMA (('IFC4X3_RC1'));
```

2020-09-18 12:27 UTC, pjanck commented on IFC 4.3/LinearPlacement_2/LinearPlacement_2.ifc
> +FILE_DESCRIPTION ((''), '2;1');
```suggestion
FILE_DESCRIPTION (('ViewDefinition []'), '2;1');
```

2020-10-13 08:58 UTC, larswik commented
I would love to merge this pull request. However, I don't seem to have the permissions...
![image](https://user-images.githubusercontent.com/25506404/95839168-fa1ae000-0d42-11eb-874f-0de007fe74af.png)

2020-10-20 06:14 UTC, merged