UT Georeferencing Survey 1
buildingSMART/Sample-Test-Files pull request #40
Opened 2020-10-05 07:56 UTC by LeeGregory12d

# IFC4.3 Unit test

## Unit test
Unit Test of Survey data
There is  a survey string of just one vertex with the string Name "SF LE" and an attribute  "Point Id" with value 3 in a Property Set called Survey. 
There is a survey string of 15 vertices with the string Name "RD ET" but no Pont Id's. The segments between the vertices are straight lines. 

The (x,y) coordinates are in the map projection MGA94 Zone 56 and z is in AHD (Australian Height Datum)

## Review requested
Questions:
1. I've used the entity IfcBuiltElement for the two survey strings but that is just a guess.
   IFCAnnotation mentions survey but that seems strange. Survey strings are fundamental for all infrastructure work, from 
   the initial data such as survey points and breaklines, cadastre,  data, boundaries, control lines, construction points and strings, conformance, machine control etc. 
 So what entities should be used ?

2. All survey strings have names  and in this example they are "SF LE" and "RD ET".
    But survey strings usually have additional information about every vertex on the string. And often additional information for every segment of a survey string.
 In this example I have only one bit of additional information "Point Id" for the one vertex survey string "SF LE" and so I put it in a Property Set called "Survey".
 But what about the more general case when there is more than one vertex in the string and attributes for each vertex and each segment ?
 How should that be coded in Ifc

@pjanck

2020-10-19 17:43 UTC, pjanck requested changes
What is the difference between Georeferencing_Survey_1 and Georeferencing_Tiny_Survey_1? I think they are duplicates, so one can be removed.

I get the same geometry in OIP:
![grafik](https://user-images.githubusercontent.com/59165496/96492019-46828600-1243-11eb-85da-34cba15fa99c.png)

2020-10-19 17:43 UTC, pjanck commented on IFC 4.3/Georeferencing_Survey_1/readme.md
> +- ifcMapConversion
Well, technically, you do have it in the file, but have filled it with default values. So I think that `IfcMapConversion` is not really covered by this unit test.

However, `IfcGeometricCurveSet` is, so please add it.

2020-10-19 17:43 UTC, pjanck commented on IFC 4.3/Georeferencing_Tiny_Survey_1/UT_one_string_one_pont.ifc
> +ISO-10303-21;
This file only differs from the file above in GUIDs and some semantic data about file's creation date. I don't see the point in having duplicate files.

2020-10-19 17:51 UTC, pjanck commented
We will address your questions in the next DEPL Tech meeting and provide you with an answer here.

2020-10-19 23:46 UTC, LeeGregory12d commented
Stefan,
Because of the initial hassle I had of not knowing about creating a Branch and doing things on Main, I redid my first two examples and submitted them as proper Branches.
So yes those two are the same.

Please keep the second (newer) one “Georeferencing_Survey_1” as it was done as a proper Branch.

Regards
Lee

Dr Lee Gregory
Managing Director
12D Solutions Pty Ltd

Creators of the 12d Model Civil and Surveying Software
and 12d Synergy for Data Management and Project Collaboration.
Ph: +61 (0)2 9970 7117
Email: lee.gregory@12d.com<mailto:lee.gregory@12d.com>
Web: www.12d.com<http://www.12d.com/aus/?utm_source=emailsig&utm_medium=email&utm_campaign=emaillink>

From: Stefan Jaud <notifications@github.com>
Sent: Tuesday, 20 October 2020 4:44 AM
To: buildingSMART/Sample-Test-Files <Sample-Test-Files@noreply.github.com>
Cc: Lee John Gregory <lee.gregory@12d.com>; Author <author@noreply.github.com>
Subject: Re: [buildingSMART/Sample-Test-Files] UT Georeferencing Survey 1 (#40)


@pjanck requested changes on this pull request.

What is the difference between Georeferencing_Survey_1 and Georeferencing_Tiny_Survey_1? I think they are duplicates, so one can be removed.

I get the same geometry in OIP:
[grafik]<https://user-images.githubusercontent.com/59165496/96492019-46828600-1243-11eb-85da-34cba15fa99c.png>

________________________________

In IFC 4.3/Georeferencing_Survey_1/readme.md<https://github.com/buildingSMART/Sample-Test-Files/pull/40#discussion_r507933824>:

> +The coordinates are in Easting, Northing and AHD for the map projection MGA94 Zone 56.

+The Horizontal and Vertical datums are specified in IfcProjectedCRS.

+

+The ifc file was written by 12d Model.

+

+### Prerequisites

+

+This scenario builds upon following other scenarios:

+- None

+

+### Content

+

+This scenario covers the following concepts and/or IFC entities:

+

+- ifcProjectedCRS

+- ifcMapConversion

Well, technically, you do have it in the file, but have filled it with default values. So I think that IfcMapConversion is not really covered by this unit test.

However, IfcGeometricCurveSet is, so please add it.

________________________________

In IFC 4.3/Georeferencing_Tiny_Survey_1/UT_one_string_one_pont.ifc<https://github.com/buildingSMART/Sample-Test-Files/pull/40#discussion_r507936881>:

> @@ -0,0 +1,74 @@

+ISO-10303-21;

This file only differs from the file above in GUIDs and some semantic data about file's creation date. I don't see the point in having duplicate files.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/buildingSMART/Sample-Test-Files/pull/40#pullrequestreview-512002132>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AOZ2E5U3563LI4HW63E7JSTSLR3ETANCNFSM4SEK7OIQ>.

Report this message as spam<https://console.mailguard.com.au/ras/1Zbq1abw7e/LYBbdWAt4FU3M0L8DXCR0/0.4>


[http://forums.12dmodel.com/downloads/images/12d_Logo.jpg]<http://www.12d.com>  [http://forums.12dmodel.com/downloads/images/Youtube_12d.jpg] <http://www.youtube.com/user/12dModelSoftware>   [http://forums.12dmodel.com/downloads/images/Twitter_12d.jpg] <http://www.twitter.com/12dmodel/>   [http://forums.12dmodel.com/downloads/images/Linkedin_12d.jpg] <http://www.linkedin.com/groups?home=&gid=3174309>   [http://forums.12dmodel.com/downloads/images/Facebook_12d.jpg] <http://www.facebook.com/pages/12d-Model/132088923475032>   [http://forums.12dmodel.com/downloads/images/Forum_12d.jpg] <http://forums.12dmodel.com/>

12d Webinars<https://www.12d.com/community/Webinars.php>

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named.
If you are not the named addressee you should not disseminate, distribute or copy this e-mail.

12d Solutions Pty Ltd is a company registered in Australia ACN 101 351 991.

2020-10-20 06:49 UTC, pjanck commented
As discussed in the Tech meeting: 

1. Please use `IfcAnnotation` as a semantic object.

2. Can you please provide an example of properties attached to individual segments/points?

2021-11-16 12:57 UTC, closed without merging